// <auto-generated />
using ConsoleEFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ConsoleEFCore.Migrations
{
    [DbContext(typeof(HospitalContext))]
    [Migration("20210827021009_1.6")]
    partial class _16
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ConsoleEFCore.Models.Consulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Diagnostico")
                        .HasColumnType("text");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("Consultas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Diagnostico = "Ficar longe de formiga",
                            PacienteId = 1
                        });
                });

            modelBuilder.Entity("ConsoleEFCore.Models.Endereco", b =>
                {
                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Logradouro")
                        .HasColumnType("text");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.HasKey("PacienteId");

                    b.ToTable("Enderecos");

                    b.HasData(
                        new
                        {
                            PacienteId = 1,
                            Logradouro = "Avenida X",
                            Numero = 304
                        });
                });

            modelBuilder.Entity("ConsoleEFCore.Models.Enfermaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int>("NumeroDeLeitos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Enfermarias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Covid",
                            NumeroDeLeitos = 10
                        });
                });

            modelBuilder.Entity("ConsoleEFCore.Models.EnfermariaMedico", b =>
                {
                    b.Property<int>("EnfermariaId")
                        .HasColumnType("integer");

                    b.Property<int>("MedicoId")
                        .HasColumnType("integer");

                    b.HasKey("EnfermariaId", "MedicoId");

                    b.HasIndex("MedicoId");

                    b.ToTable("EnfermariaMedico");

                    b.HasData(
                        new
                        {
                            EnfermariaId = 1,
                            MedicoId = 1
                        });
                });

            modelBuilder.Entity("ConsoleEFCore.Models.Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Especialidade")
                        .HasColumnType("text");

                    b.Property<int>("Idade")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Medicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Especialidade = "Clínico geral",
                            Idade = 39,
                            Nome = "Roberto Souza"
                        });
                });

            modelBuilder.Entity("ConsoleEFCore.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Alergias")
                        .HasColumnType("text");

                    b.Property<int>("Idade")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<int>("Sexo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Pacientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alergias = "Abelha;Formiga",
                            Idade = 38,
                            Nome = "Carlos Eduardo",
                            Sexo = 0
                        });
                });

            modelBuilder.Entity("ConsoleEFCore.Models.Consulta", b =>
                {
                    b.HasOne("ConsoleEFCore.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ConsoleEFCore.Models.Endereco", b =>
                {
                    b.HasOne("ConsoleEFCore.Models.Paciente", "Paciente")
                        .WithOne("Endereco")
                        .HasForeignKey("ConsoleEFCore.Models.Endereco", "PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ConsoleEFCore.Models.EnfermariaMedico", b =>
                {
                    b.HasOne("ConsoleEFCore.Models.Enfermaria", "Enfermaria")
                        .WithMany("EnfermariaMedico")
                        .HasForeignKey("EnfermariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleEFCore.Models.Medico", "Medico")
                        .WithMany("Enfermarias")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enfermaria");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("ConsoleEFCore.Models.Enfermaria", b =>
                {
                    b.Navigation("EnfermariaMedico");
                });

            modelBuilder.Entity("ConsoleEFCore.Models.Medico", b =>
                {
                    b.Navigation("Enfermarias");
                });

            modelBuilder.Entity("ConsoleEFCore.Models.Paciente", b =>
                {
                    b.Navigation("Endereco");
                });
#pragma warning restore 612, 618
        }
    }
}
